cmd_/home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/objtool/elf.o := gcc -Wp,-MD,/home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/objtool/.elf.o.d -Wp,-MT,/home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/objtool/elf.o -Werror -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -Wstrict-aliasing=3 -Wshadow -Wno-switch-default -Wno-switch-enum -Wno-packed -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu89 -O2 -I/home/trb/sdk/imm/staging_dir/host/include -Wall -Wmissing-prototypes -Wstrict-prototypes -g -I/home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include -I/home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/arch/x86/include/uapi -I/home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/arch/x86/include -I/home/trb/sdk/imm/staging_dir/host/include/libelf -I/home/trb/sdk/imm/staging_dir/host/include -I/home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/lib -D"BUILD_STR(s)=$(pound)s" -c -o /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/objtool/elf.o elf.c

source_/home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/objtool/elf.o := elf.c

deps_/home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/objtool/elf.o := \
  /usr/include/stdc-predef.h \
  /usr/include/x86_64-linux-gnu/sys/types.h \
  /usr/include/features.h \
  /usr/include/features-time64.h \
  /usr/include/x86_64-linux-gnu/bits/wordsize.h \
  /usr/include/x86_64-linux-gnu/bits/timesize.h \
  /usr/include/x86_64-linux-gnu/sys/cdefs.h \
  /usr/include/x86_64-linux-gnu/bits/long-double.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs-64.h \
  /usr/include/x86_64-linux-gnu/bits/types.h \
  /usr/include/x86_64-linux-gnu/bits/typesizes.h \
  /usr/include/x86_64-linux-gnu/bits/time64.h \
  /usr/include/x86_64-linux-gnu/bits/types/clock_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/clockid_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/time_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/timer_t.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h \
  /usr/include/x86_64-linux-gnu/bits/stdint-intn.h \
  /home/trb/sdk/imm/staging_dir/host/include/endian.h \
  /home/trb/sdk/imm/staging_dir/host/include/byteswap.h \
  /usr/include/byteswap.h \
  /usr/include/x86_64-linux-gnu/bits/byteswap.h \
  /usr/include/endian.h \
  /usr/include/x86_64-linux-gnu/bits/endian.h \
  /usr/include/x86_64-linux-gnu/bits/endianness.h \
  /usr/include/x86_64-linux-gnu/bits/uintn-identity.h \
  /usr/include/x86_64-linux-gnu/sys/select.h \
  /usr/include/x86_64-linux-gnu/bits/select.h \
  /usr/include/x86_64-linux-gnu/bits/types/sigset_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__sigset_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_timeval.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_timespec.h \
  /usr/include/x86_64-linux-gnu/bits/select2.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h \
  /usr/include/x86_64-linux-gnu/bits/thread-shared-types.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes-arch.h \
  /usr/include/x86_64-linux-gnu/bits/atomic_wide_counter.h \
  /usr/include/x86_64-linux-gnu/bits/struct_mutex.h \
  /usr/include/x86_64-linux-gnu/bits/struct_rwlock.h \
  /usr/include/x86_64-linux-gnu/sys/stat.h \
  /usr/include/x86_64-linux-gnu/bits/stat.h \
  /usr/include/x86_64-linux-gnu/bits/struct_stat.h \
  /usr/include/fcntl.h \
  /usr/include/x86_64-linux-gnu/bits/fcntl.h \
  /usr/include/x86_64-linux-gnu/bits/fcntl-linux.h \
  /usr/include/x86_64-linux-gnu/bits/fcntl2.h \
  /usr/include/stdio.h \
  /usr/include/x86_64-linux-gnu/bits/libc-header-start.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/stdarg.h \
  /usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__FILE.h \
  /usr/include/x86_64-linux-gnu/bits/types/FILE.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h \
  /usr/include/x86_64-linux-gnu/bits/stdio_lim.h \
  /usr/include/x86_64-linux-gnu/bits/floatn.h \
  /usr/include/x86_64-linux-gnu/bits/floatn-common.h \
  /usr/include/x86_64-linux-gnu/bits/stdio.h \
  /usr/include/x86_64-linux-gnu/bits/stdio2.h \
  /usr/include/stdlib.h \
  /usr/include/x86_64-linux-gnu/bits/waitflags.h \
  /usr/include/x86_64-linux-gnu/bits/waitstatus.h \
  /usr/include/alloca.h \
  /usr/include/x86_64-linux-gnu/bits/stdlib-bsearch.h \
  /usr/include/x86_64-linux-gnu/bits/stdlib-float.h \
  /usr/include/x86_64-linux-gnu/bits/stdlib.h \
  /usr/include/string.h \
  /usr/include/x86_64-linux-gnu/bits/types/locale_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__locale_t.h \
  /usr/include/strings.h \
  /usr/include/x86_64-linux-gnu/bits/strings_fortified.h \
  /usr/include/x86_64-linux-gnu/bits/string_fortified.h \
  /usr/include/unistd.h \
  /usr/include/x86_64-linux-gnu/bits/posix_opt.h \
  /usr/include/x86_64-linux-gnu/bits/environments.h \
  /usr/include/x86_64-linux-gnu/bits/confname.h \
  /usr/include/x86_64-linux-gnu/bits/getopt_posix.h \
  /usr/include/x86_64-linux-gnu/bits/getopt_core.h \
  /usr/include/x86_64-linux-gnu/bits/unistd.h \
  /usr/include/x86_64-linux-gnu/bits/unistd_ext.h \
  /usr/include/errno.h \
  /usr/include/x86_64-linux-gnu/bits/errno.h \
  /usr/include/linux/errno.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/arch/x86/include/uapi/asm/errno.h \
  /usr/include/asm-generic/errno.h \
  /usr/include/asm-generic/errno-base.h \
  elf.h \
  /home/trb/sdk/imm/staging_dir/host/include/libelf/gelf.h \
  /home/trb/sdk/imm/staging_dir/host/include/libelf/libelf.h \
  /home/trb/sdk/imm/staging_dir/host/include/libelf/sys_elf.h \
  /home/trb/sdk/imm/staging_dir/host/include/elf.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/x86_64-linux-gnu/bits/wchar.h \
  /usr/include/x86_64-linux-gnu/bits/stdint-uintn.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/linux/list.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/stdbool.h \
  /usr/include/x86_64-linux-gnu/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/arch/x86/include/uapi/asm/bitsperlong.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/asm-generic/bitsperlong.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/x86_64-linux-gnu/asm/posix_types.h \
  /usr/include/x86_64-linux-gnu/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/linux/poison.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/linux/kernel.h \
  /usr/include/assert.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/linux/compiler.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/linux/compiler-gcc.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/linux/hashtable.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/linux/bitops.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/limits.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/syslimits.h \
  /usr/include/limits.h \
  /usr/include/x86_64-linux-gnu/bits/posix1_lim.h \
  /usr/include/x86_64-linux-gnu/bits/local_lim.h \
  /usr/include/linux/limits.h \
  /usr/include/x86_64-linux-gnu/bits/pthread_stack_min-dynamic.h \
  /usr/include/x86_64-linux-gnu/bits/pthread_stack_min.h \
  /usr/include/x86_64-linux-gnu/bits/posix2_lim.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/linux/bits.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/linux/const.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/uapi/linux/const.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/asm-generic/bitops.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/asm-generic/bitops/__ffs.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/asm-generic/bitops/__ffz.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/asm-generic/bitops/fls.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/asm-generic/bitops/__fls.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/asm-generic/bitops/fls64.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/asm-generic/bitops/find.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/asm-generic/bitops/hweight.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/asm-generic/bitops/arch_hweight.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/asm-generic/bitops/const_hweight.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/asm-generic/bitops/atomic.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/asm-generic/bitops/non-atomic.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/linux/hash.h \
  /home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/include/linux/log2.h \
  warn.h \

/home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/objtool/elf.o: $(deps_/home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/objtool/elf.o)

$(deps_/home/trb/sdk/imm/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.230/tools/objtool/elf.o):
